include = []

[[worlds]]
name = "Default"
include = "optout"


[[handles]]
name = "Frame"
context = [{name="glcontxt", type="GLContext"}]

[[components]]
name = "MeshRenderer"
handles = [{every="Frame", callback="render", with = ["glcontext"]}]